# Load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


include: "rules/common.smk"


PAIRED_END = paired_end()
SAMPLES = import_samples(PAIRED_END)
CSV = pd.read_csv("config/samples.csv")
CONDITIONS = conditions(CSV)


# Load rules
# -----------------------------------------------------
include: "rules/process_reads.smk"
include: "rules/qc.smk"
include: "rules/resources.smk"
include: "rules/bigwig.smk"


# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# Target rules
# -----------------------------------------------------
rule all:
    input:
        #"results/multiqc/multiqc_report.html",
        expand(
            "results/bismark/{sample}/{sample}.deduplicated.nucleotide_stats.txt",
            sample=SAMPLES,
        ),
        expand(
            "results/bismark/{sample}/{sample}.deduplicated.M-bias.txt", sample=SAMPLES
        ),
        expand("results/bigwig/{condition}.bw", condition=CONDITIONS),
